import { 
  UserProfile, 
  TrustedPerson, 
  Camera, 
  Detection, 
  EmergencyContact, 
  Incident, 
  AppNotification, 
  UserSettings,
  Zone,
  SecuritySensor,
  DeviceHealthItem,
  DailySecurityBrief
} from '../types';

export const INITIAL_PROFILE: UserProfile = {
  id: 'usr-bhaskar-101',
  name: 'Bhaskar',
  full_name: 'Bhaskar',
  email: 'bhaskar@example.com',
  phone: '+91 98765 43210',
  home_name: 'Bhaskar Home',
  home_address: 'Villa 42, Palm Meadows, Whitefield, Bengaluru',
  avatar_url: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?auto=format&fit=crop&w=300&q=80',
  created_at: new Date(Date.now() - 60 * 86400000).toISOString(),
};

export const INITIAL_TRUSTED_PEOPLE: TrustedPerson[] = [];

export const INITIAL_ZONES: Zone[] = [
  {
    id: 'zone-entrance',
    name: 'Main Entrance',
    type: 'entrance',
    sensitivity: 'high',
    privacy_level: 'standard',
    is_monitored: true,
    camera_ids: ['cam-1'],
    sensor_ids: ['sensor-door-1', 'sensor-pir-1'],
    allowed_roles: ['owner', 'family', 'regular_visitor', 'service_delivery'],
    notes: 'Primary visitor approach, package dropoff & front gate entry.',
  },
  {
    id: 'zone-living',
    name: 'Living Room',
    type: 'living',
    sensitivity: 'medium',
    privacy_level: 'standard',
    is_monitored: true,
    camera_ids: ['cam-2'],
    sensor_ids: ['sensor-radar-1'],
    allowed_roles: ['owner', 'family', 'regular_visitor'],
    notes: 'Central common area. Privacy mode can pause recording when home.',
  },
  {
    id: 'zone-backyard',
    name: 'Backyard & Garden',
    type: 'backyard',
    sensitivity: 'high',
    privacy_level: 'standard',
    is_monitored: true,
    camera_ids: ['cam-3'],
    sensor_ids: ['sensor-pir-2'],
    allowed_roles: ['owner', 'family'],
    notes: 'Perimeter boundary. Monitored strictly at night.',
  },
  {
    id: 'zone-garage',
    name: 'Garage & Driveway',
    type: 'garage',
    sensitivity: 'medium',
    privacy_level: 'standard',
    is_monitored: true,
    camera_ids: [],
    sensor_ids: ['sensor-door-2'],
    allowed_roles: ['owner', 'family'],
    notes: 'Vehicle entry and side gate access.',
  },
  {
    id: 'zone-bedroom',
    name: 'Master Suite',
    type: 'bedroom',
    sensitivity: 'low',
    privacy_level: 'high_privacy',
    is_monitored: false,
    camera_ids: [],
    sensor_ids: [],
    allowed_roles: ['owner'],
    notes: 'High-privacy zone. Video cameras strictly restricted.',
  },
];

export const INITIAL_SENSORS: SecuritySensor[] = [
  {
    id: 'sensor-door-1',
    name: 'Front Door Contact Sensor',
    zone: 'Main Entrance',
    type: 'door_window',
    status: 'closed',
    battery_percent: 94,
    last_activity: '12 min ago',
  },
  {
    id: 'sensor-pir-1',
    name: 'Front Porch PIR Motion',
    zone: 'Main Entrance',
    type: 'pir_motion',
    status: 'clear',
    battery_percent: 88,
    last_activity: '2 min ago',
  },
  {
    id: 'sensor-radar-1',
    name: 'Living Room mmWave Sensor',
    zone: 'Living Room',
    type: 'radar_mmwave',
    status: 'clear',
    battery_percent: 100,
    last_activity: '45 min ago',
  },
  {
    id: 'sensor-pir-2',
    name: 'Backyard Perimeter Motion',
    zone: 'Backyard & Garden',
    type: 'pir_motion',
    status: 'clear',
    battery_percent: 91,
    last_activity: '3 hours ago',
  },
  {
    id: 'sensor-lock-1',
    name: 'Smart Deadbolt Lock',
    zone: 'Main Entrance',
    type: 'smart_lock',
    status: 'closed',
    battery_percent: 89,
    last_activity: '12 min ago',
  },
];

export const INITIAL_CAMERAS: Camera[] = [
  {
    id: 'cam-1',
    user_id: 'usr-bhaskar-101',
    name: 'Main Entrance Doorbell',
    location: 'Front Door',
    zone: 'Main Entrance',
    brand: 'SANJAYA Vision Pro',
    camera_type: 'doorbell',
    connection_type: 'sanjaya_cam',
    stream_url: 'rtsp://sanjaya-edge.local/live/ch1',
    status: 'online',
    is_simulation: true,
    is_tampered: false,
    siren_active: false,
    spotlight_active: false,
    created_at: new Date(Date.now() - 40 * 86400000).toISOString(),
  },
  {
    id: 'cam-2',
    user_id: 'usr-bhaskar-101',
    name: 'Living Room Dome',
    location: 'Indoor',
    zone: 'Living Room',
    brand: 'Hikvision ONVIF',
    camera_type: 'dome',
    connection_type: 'onvif',
    stream_url: 'rtsp://sanjaya-edge.local/live/ch2',
    status: 'offline',
    is_simulation: true,
    is_tampered: false,
    tamper_reason: 'Power standby in Home Mode (Privacy Protected)',
    created_at: new Date(Date.now() - 35 * 86400000).toISOString(),
  },
  {
    id: 'cam-3',
    user_id: 'usr-bhaskar-101',
    name: 'Backyard Perimeter Bullet',
    location: 'Back Garden',
    zone: 'Backyard & Garden',
    brand: 'Dahua 4K Ultra',
    camera_type: 'bullet',
    connection_type: 'rtsp',
    stream_url: 'rtsp://sanjaya-edge.local/live/ch3',
    status: 'online',
    is_simulation: true,
    is_tampered: false,
    created_at: new Date(Date.now() - 20 * 86400000).toISOString(),
  },
];

export const INITIAL_EMERGENCY_CONTACTS: EmergencyContact[] = [
  {
    id: 'ec-1',
    user_id: 'usr-bhaskar-101',
    name: 'Ravi',
    relationship: 'Father',
    phone: '+91 98765 43210',
    priority: 1,
    created_at: new Date(Date.now() - 30 * 86400000).toISOString(),
  },
  {
    id: 'ec-2',
    user_id: 'usr-bhaskar-101',
    name: 'Sneha',
    relationship: 'Sister',
    phone: '+91 87654 32109',
    priority: 2,
    created_at: new Date(Date.now() - 25 * 86400000).toISOString(),
  },
  {
    id: 'ec-3',
    user_id: 'usr-bhaskar-101',
    name: 'Avi',
    relationship: 'Friend',
    phone: '+91 76543 21098',
    priority: 3,
    created_at: new Date(Date.now() - 15 * 86400000).toISOString(),
  },
];

export const INITIAL_DETECTIONS: Detection[] = [
  {
    id: 'det-101',
    camera_id: 'cam-1',
    camera_name: 'Main Entrance Doorbell',
    user_id: 'usr-bhaskar-101',
    person_type: 'unknown',
    confidence: 0.91,
    zone: 'Main Entrance',
    category: 'person',
    dwell_time_seconds: 45,
    risk_level: 'MEDIUM',
    snapshot_url: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=600&q=80',
    detected_at: new Date(Date.now() - 2 * 60000).toISOString(),
    bounding_box: { x: 0.38, y: 0.22, width: 0.24, height: 0.62 },
    notes: 'Approached front entryway porch; observed waiting at door.',
  },
];

export const INITIAL_INCIDENTS: Incident[] = [
  {
    id: 'inc-1',
    user_id: 'usr-bhaskar-101',
    detection_id: 'det-101',
    type: 'unknown_detection',
    status: 'active',
    latitude: 12.9716,
    longitude: 77.5946,
    location_address: 'Villa 42, Palm Meadows, Whitefield, Bengaluru',
    started_at: new Date(Date.now() - 2 * 60000).toISOString(),
    notes: 'Unknown visitor approached front porch. Face embeddings do not match any enrolled trusted person.',
    risk_level: 'MEDIUM',
    risk_factors: [
      'Unrecognized visitor',
      'Approached front entryway',
      'Dwell time exceeds 40 seconds',
      'No scheduled delivery on file',
    ],
    ai_explanation: 'An unknown person has been standing near the front door for 45 seconds. The visitor pressed no chime and is checking the entrance area. Home is currently in Home Secure mode.',
    who: 'Unknown Person (Temporary ID #24)',
    where: 'Main Entrance · Front Porch',
    when: '2 minutes ago (Daytime)',
    what: 'Visitor standing at front door looking around',
    dwell_time_seconds: 45,
    home_mode_at_time: 'home',
    classification: 'UNUSUAL',
    recommended_actions: [
      'Initiate Two-Way Talk to ask visitor their purpose',
      'Switch on Entrance Spotlight if dark',
      'Enroll person into Trusted Registry if known friend',
    ],
    behaviour_sequence: [
      { id: 'b-1', timestamp: new Date(Date.now() - 2 * 60000).toISOString(), action: 'Motion detected along pathway', zone: 'Main Entrance', dwell_seconds: 8 },
      { id: 'b-2', timestamp: new Date(Date.now() - 1.8 * 60000).toISOString(), action: 'Person approaches front gate', zone: 'Main Entrance', dwell_seconds: 12 },
      { id: 'b-3', timestamp: new Date(Date.now() - 1.5 * 60000).toISOString(), action: 'Stepped onto front porch', zone: 'Main Entrance', dwell_seconds: 15 },
      { id: 'b-4', timestamp: new Date(Date.now() - 1.2 * 60000).toISOString(), action: 'Dwells near door handle and glances around', zone: 'Main Entrance', dwell_seconds: 10 },
    ],
    camera_path: [
      {
        camera_id: 'cam-1',
        camera_name: 'Main Entrance Doorbell',
        timestamp: new Date(Date.now() - 2 * 60000).toISOString(),
        zone: 'Main Entrance',
        snapshot_url: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=600&q=80',
        dwell_seconds: 45,
      },
    ],
    sensors_triggered: ['Front Porch PIR Motion', 'Main Entrance Doorbell'],
    timeline: [
      {
        id: 'tl-1',
        timestamp: new Date(Date.now() - 2 * 60000).toISOString(),
        title: 'Person detected',
        description: 'PIR motion sensor and AI neural vision detected human figure at Main Entrance',
        type: 'detection',
        camera_name: 'Main Entrance Doorbell',
        zone: 'Main Entrance',
      },
      {
        id: 'tl-2',
        timestamp: new Date(Date.now() - 1.9 * 60000).toISOString(),
        title: 'Classified as unknown',
        description: 'Face embeddings did not match any enrolled trusted person (Confidence: 91%)',
        type: 'classification',
        camera_name: 'Main Entrance Doorbell',
        zone: 'Main Entrance',
      },
      {
        id: 'tl-3',
        timestamp: new Date(Date.now() - 1.5 * 60000).toISOString(),
        title: 'Contextual risk calculated: MEDIUM',
        description: 'Risk Engine evaluated: unknown visitor + 45s porch dwell time + day hours',
        type: 'classification',
      },
      {
        id: 'tl-4',
        timestamp: new Date(Date.now() - 1.4 * 60000).toISOString(),
        title: 'Homeowner verification dispatched',
        description: 'System sent priority in-app awareness notification to homeowner',
        type: 'viewed',
      },
    ],
  },
  {
    id: 'inc-2',
    user_id: 'usr-bhaskar-101',
    type: 'sos_activated',
    status: 'cancelled',
    latitude: 12.9716,
    longitude: 77.5946,
    location_address: 'Villa 42, Palm Meadows, Whitefield, Bengaluru',
    started_at: new Date(Date.now() - 16 * 3600000).toISOString(),
    resolved_at: new Date(Date.now() - 15.9 * 3600000).toISOString(),
    notes: 'SOS triggered manually and cancelled by user within 12 seconds.',
    timeline: [
      {
        id: 'tl-201',
        timestamp: new Date(Date.now() - 16 * 3600000).toISOString(),
        title: 'SOS countdown initiated',
        description: 'Homeowner pressed SOS panic trigger',
        type: 'sos',
      },
      {
        id: 'tl-202',
        timestamp: new Date(Date.now() - 15.9 * 3600000).toISOString(),
        title: 'SOS cancelled by homeowner',
        description: 'User pressed Cancel SOS before escalation dispatch',
        type: 'cancelled',
      },
    ],
  },
  {
    id: 'inc-3',
    user_id: 'usr-bhaskar-101',
    type: 'unknown_detection',
    status: 'resolved',
    latitude: 12.9716,
    longitude: 77.5946,
    location_address: 'Villa 42, Palm Meadows, Whitefield, Bengaluru',
    started_at: new Date(Date.now() - 28 * 3600000).toISOString(),
    resolved_at: new Date(Date.now() - 27.8 * 3600000).toISOString(),
    notes: 'Courier delivery verified by homeowner over two-way audio. Closed normally.',
    risk_level: 'LOW',
    risk_factors: ['Daytime delivery', 'Package placed at porch', 'Immediate departure'],
    ai_explanation: 'Delivery personnel dropped package on porch and departed within 20 seconds. No threat detected.',
    who: 'Courier / Delivery Personnel',
    where: 'Main Entrance',
    when: 'Yesterday 02:15 PM',
    what: 'Package delivery dropped off safely',
    dwell_time_seconds: 20,
    home_mode_at_time: 'home',
    classification: 'NORMAL',
    timeline: [
      {
        id: 'tl-301',
        timestamp: new Date(Date.now() - 28 * 3600000).toISOString(),
        title: 'Person detected',
        description: 'Motion sensor detected courier approaching delivery box',
        type: 'detection',
      },
      {
        id: 'tl-302',
        timestamp: new Date(Date.now() - 27.9 * 3600000).toISOString(),
        title: 'Homeowner viewed live camera',
        description: 'Two-way audio talk session initiated for 24 seconds',
        type: 'viewed',
      },
      {
        id: 'tl-303',
        timestamp: new Date(Date.now() - 27.8 * 3600000).toISOString(),
        title: 'Incident closed',
        description: 'Visitor departed; marked resolved by homeowner',
        type: 'resolved',
      },
    ],
  },
];

export const INITIAL_NOTIFICATIONS: AppNotification[] = [
  {
    id: 'notif-1',
    user_id: 'usr-bhaskar-101',
    type: 'security',
    category: 'security',
    title: 'Unknown person detected',
    message: 'Main Entrance · 2 min ago · Risk: MEDIUM. Review snapshot and live view.',
    read: false,
    created_at: new Date(Date.now() - 2 * 60000).toISOString(),
    metadata: { detection_id: 'det-101', zone: 'Main Entrance' },
  },
  {
    id: 'notif-3',
    user_id: 'usr-bhaskar-101',
    type: 'emergency',
    category: 'emergency',
    title: 'SOS cancelled',
    message: 'Main Entrance · Yesterday 08:04 PM. Panic timer safely cancelled.',
    read: true,
    created_at: new Date(Date.now() - 16 * 3600000).toISOString(),
    metadata: { incident_id: 'inc-2' },
  },
  {
    id: 'notif-4',
    user_id: 'usr-bhaskar-101',
    type: 'system',
    category: 'system',
    title: 'Edge neural engine active',
    message: 'Edge neural engine v2.4 initialized with 28ms local inference latency.',
    read: true,
    created_at: new Date(Date.now() - 24 * 3600000).toISOString(),
  },
];

export const INITIAL_DAILY_BRIEF: DailySecurityBrief = {
  date: 'Today',
  overall_status: 'secure',
  headline: 'Home remained secure throughout the day',
  normal_events_count: 14,
  deliveries_count: 2,
  family_arrivals_count: 3,
  critical_incidents_count: 0,
  highlights: [
    'No critical perimeter breaches or glass break events detected',
    '2 verified parcel dropoffs at Main Entrance',
    '1 active verification incident currently awaiting homeowner review',
  ],
  unusual_activity_summary: 'Main Entrance: An unrecognized person was detected 2 minutes ago. Risk evaluated as MEDIUM due to dwelling at porch.',
};

export const INITIAL_DEVICE_HEALTH: DeviceHealthItem[] = [
  {
    id: 'dev-1',
    device_name: 'Main Entrance Doorbell',
    device_type: 'camera',
    status: 'healthy',
    zone: 'Main Entrance',
    details: 'Online · RTSP/WebRTC stream active (28ms latency) · Wi-Fi 92%',
    battery_percent: 100,
    last_ping: 'Just now',
  },
  {
    id: 'dev-2',
    device_name: 'Living Room Dome',
    device_type: 'camera',
    status: 'warning',
    zone: 'Living Room',
    details: 'Offline · In Home Privacy Sleep mode. Will activate when Away.',
    last_ping: '35 min ago',
  },
  {
    id: 'dev-3',
    device_name: 'Backyard Perimeter Bullet',
    device_type: 'camera',
    status: 'healthy',
    zone: 'Backyard & Garden',
    details: 'Online · Infrared Night Vision ready · 4K stream active',
    last_ping: '1 min ago',
  },
  {
    id: 'dev-4',
    device_name: 'Front Door Smart Deadbolt',
    device_type: 'sensor',
    status: 'healthy',
    zone: 'Main Entrance',
    details: 'Locked · Zigbee Mesh connected',
    battery_percent: 89,
    last_ping: '12 min ago',
  },
  {
    id: 'dev-5',
    device_name: 'Front Porch PIR Motion',
    device_type: 'sensor',
    status: 'healthy',
    zone: 'Main Entrance',
    details: 'Operational · Motion sensitivity High',
    battery_percent: 88,
    last_ping: '2 min ago',
  },
];

export const INITIAL_SETTINGS: UserSettings = {
  user_id: 'usr-bhaskar-101',
  face_recognition_enabled: true,
  detection_history_days: 30,
  location_sharing_sos: true,
  location_sharing_enabled: true,
  camera_access_enabled: true,
  sos_countdown_seconds: 30,
  alert_audio_enabled: true,
  indoor_monitor_mode: false,
  confidence_threshold: 0.85,
  unknown_person_alert: true,
  snapshot_retention_days: 30,
  local_storage_only: true,
  // Privacy Center Extensions
  ai_processing_mode: 'edge',
  guest_privacy_mode: false,
  audio_monitoring_enabled: true,
  video_retention_days: 7,
  tamper_alerts_enabled: true,
  escalation_wait_minutes: 5,
};
